// This .js file is auto-generated by `createCesium()` from VeRoViz
// Display nodes for cesium application

function displayNodes() {
    var pin = new Array;
    pin[0] = viewer.entities.add({
        name : '0',
        parent : nodePins,
        description : '1',
        position : Cesium.Cartesian3.fromDegrees(33.707391123133924, -13.938121729120823),
        billboard : {
            image : pinBuilder.fromText('0', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[1] = viewer.entities.add({
        name : '1',
        parent : nodePins,
        description : '2',
        position : Cesium.Cartesian3.fromDegrees(33.866651350321206, -13.89214715151327),
        billboard : {
            image : pinBuilder.fromText('1', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[2] = viewer.entities.add({
        name : '2',
        parent : nodePins,
        description : '3',
        position : Cesium.Cartesian3.fromDegrees(33.89548294317409, -13.996076624351828),
        billboard : {
            image : pinBuilder.fromText('2', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

    pin[3] = viewer.entities.add({
        name : '3',
        parent : nodePins,
        description : '4',
        position : Cesium.Cartesian3.fromDegrees(33.73896858197279, -14.015391679272259),
        billboard : {
            image : pinBuilder.fromText('3', Cesium.Color.BLUE, 40).toDataURL(),
            verticalOrigin : Cesium.VerticalOrigin.BOTTOM
        }
    });

}