// This .js file is auto-generated by `createCesium()` from VeRoViz
// The configs for cesium application go to here

function setConfigs() {
    viewer.camera.flyTo({
        destination: Cesium.Rectangle.fromDegrees(103.883883, 30.485490, 104.307100, 30.805523) 
    });
    viewer.clock.currentTime = Cesium.JulianDate.addSeconds('2022-05-26T08:00:00Z', 0, new Cesium.JulianDate());
    allIDs = [
        'o-Blue Car-/veroviz/models/car_blue.gltf-move', 
        'o-Green Car-/veroviz/models/car_green.gltf-move', 
        'o-Red Car-/veroviz/models/car_red.gltf-move'    
    ];
    orientationIDs = [
        'o-Blue Car-/veroviz/models/car_blue.gltf-move', 
        'o-Green Car-/veroviz/models/car_green.gltf-move', 
        'o-Red Car-/veroviz/models/car_red.gltf-move'    
    ];
    czmlRouteFile = '/veroviz/demo/routes.czml';
    runRoutes(czmlRouteFile, allIDs, orientationIDs);
objectInfo['Blue Car-/veroviz/models/car_blue.gltf'] = {
    label : 'Blue Car (/veroviz/models/car_blue.gltf)', 
    childModels : ['o-Blue Car-/veroviz/models/car_blue.gltf-move'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['Green Car-/veroviz/models/car_green.gltf'] = {
    label : 'Green Car (/veroviz/models/car_green.gltf)', 
    childModels : ['o-Green Car-/veroviz/models/car_green.gltf-move'],
    scale : 100, 
    minPxSize : 75 
}; 
objectInfo['Red Car-/veroviz/models/car_red.gltf'] = {
    label : 'Red Car (/veroviz/models/car_red.gltf)', 
    childModels : ['o-Red Car-/veroviz/models/car_red.gltf-move'],
    scale : 100, 
    minPxSize : 75 
}; 
    registerObjects(objectInfo); 
}